### PR TITLE
Update unified-bridge.md

### LINKED ISSUE #2477: ..
https://github.com/maticnetwork/polygon-token-list/issues/671

### PR DESCRIPTION
**Pull request by Jaime-N**
Revised unified bridge documentation to include: 
- Data structures
- Components
- Interface
- Bridge and call as well as several code walkthroughs

### CODE REVIEW

**Review by mitchpolygon — APPROVED** [review]

**Review by Sharonbc01 — COMMENTED** [review]
looks good

**Review by fukinbubba — COMMENTED** [review]
changed

**Review by Jaime-N — COMMENTED** [review]
looks good

**Review by fukinbubba — COMMENTED** [review]
k

**Comment by fukinbubba** [comment]
trying

**Comment by fukinbubba** [comment]
k

**Comment by fukinbubba** [comment]
k

**Comment by fukinbubba** [comment]
k

**Comment by fukinbubba** [comment]
k

**Pull request merged**
