### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by abdullahvenly**
Updated the content disclaimer as it was not the right style.

### CODE REVIEW

**Comment by abdullahvenly** [comment]
Hi @kmurphypolygon 

I have made a slight update to the index page.

Also, I was meaning to ask you where I could add Venly's NFT-API service which allows you to create Polygon smart contracts and mint NFTs on the Polygon chain. Link: https://docs.venly.io/docs/nft-api-getting-started

**Review by kmurphypolygon — APPROVED** [review]
LGTM

**Comment by kmurphypolygon** [comment]
> Hi @kmurphypolygon
> 
> I have made a slight update to the index page.
> 
> Also, I was meaning to ask you where I could add Venly's NFT-API service which allows you to create Polygon smart contracts and mint NFTs on the Polygon chain. Link: https://docs.venly.io/docs/nft-api-getting-started

Thanks for the update.

Great idea, thank you for the addition to our docs. Could you add it as an external link in the `mkdocs.yml` config file under third party tutorials, raise a new PR and request an approve.

Screenshot 2024-04-17 at 15 57 26

**Comment by abdullahvenly** [comment]
@kmurphypolygon sounds great, thanks for the tip!

**Pull request merged**
