### PR TITLE
Added section for the graph: quick start full guide

### PR DESCRIPTION
**Pull request by alinobrasil**
This PR contains changes for: 

- `mkdocs.yml`: Added navigation item conforming to alphabetical order
- `tools/thegraph.md`: Contains a full walk through on how to setup a subgraph

Please let me know if anything needs to be updated to get published.

### CODE REVIEW

**Review by vestival — COMMENTED** [review]
It looks good to me!!

**Review by mitchpolygon — APPROVED** [review]

**Comment by vestival** [comment]
@alinobrasil  can you please make sure the commit is signed? https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification

**Comment by alinobrasil** [comment]
@vestival I just added a signed commit!

**Comment by alinobrasil** [comment]
All commits are signed now @vestival

**Comment by Jenibabi1984** [comment]
🫠

**Pull request merged**
