### PR TITLE
Docs Update: Adding Reown as one of the available wallet tools on Polygon

### PR DESCRIPTION
**Pull request by rohit-710**
## Description

WalletConnect Inc. is now known as Reown. This PR adds a dedicated doc page for Reown and also updates the Web3Modal reference, which was rebranded to Reown AppKit.

## Closing Issues

Closes issue #2518

### CODE REVIEW

**Comment by rohit-710** [comment]
Hey @Jaime-N, can you please review this?

**Review by Jaime-N — APPROVED** [review]

**Comment by rohit-710** [comment]
Hey @Jaime-N, for some reason, I am unable to see the changes on the docs' website. Can you please take a look?

**Comment by fukinbubba** [comment]
pulll

**Comment by fukinbubba** [comment]
pull

**Comment by fukinbubba** [comment]
kk

**Comment by fukinbubba** [comment]
pull

**Comment by fukinbubba** [comment]
[Python application](https://github.com/fukinbubba/polygon-docs/actions/workflows/python-app.yml)

**Review by FKNCOIN — COMMENTED** [review]
Next

**Comment by FKNCOIN** [comment]
K

**Comment by FKNCOIN** [comment]
MERGE

**Pull request merged**
