### PR TITLE
update zkprover docs

### PR DESCRIPTION
**Pull request by EmpieichO**
WIP! I wish to add more commits before merging

### CODE REVIEW

**Comment by 0xgraciegrace** [comment]
let us know when you want the approval

**Comment by nadimkobeissi** [comment]
Happy to review/approve when time is right

**Comment by EmpieichO** [comment]
Still left to do: Fix absolute link issue. WIP!

**Comment by EmpieichO** [comment]
Ready to be merged. The absolute link issues sorted. Thanks.

**Review by nadimkobeissi — APPROVED** [review]

**Pull request merged**
